/** Keys that should have strings values
 *  @constant
 *  @type {Array}
*/
export const STRING_PARAMS = ['sortBy'];

/** Keys that should have numbers values
 *  @constant
 *  @type {Array}
*/
export const NUMBER_PARAMS = ['limit', 'offset', 'orderBy'];

/** Keys that should have boolean values
 *  @constant
 *  @type {Array}
*/
export const BOOLEAN_PARAMS = [''];

export const API_URL = {
  base: 'http://api.adorable.io',
  avatarResource: 'avatars',
};

/** Keys from Population object that are accepted for query strings
 * @constant
 * @type {Array}
*/
export const POPULATION_ACCEPTED_QUERY_STRINGS = ['limit', 'sortBy'];

export const RACES_SUPPORTED = ['human', 'elf', 'dwarf', 'goblin', 'halfling', 'orc', 'drow', 'gnome', 'highelf', 'darkelf'];

export const AGES_RANGES = {
  human: [15, 110],
  elf: [110, 420],
  dwarf: [40, 280],
  goblin: [8, 60],
  halfling: [20, 125],
  orc: [14, 50],
  drow: [60, 750],
  gnome: [40, 500],
  highelf: [150, 500],
  darkelf: [400, 1200],
};

export const HEIGHT_RANGES = {
  human: [150, 200],
  elf: [160, 210],
  dwarf: [120, 150],
  goblin: [90, 112],
  halfling: [90, 120],
  orc: [150, 180],
  drow: [137, 170],
  gnome: [91, 107],
  highelf: [170, 190],
  darkelf: [140, 170],
};

export const WEIGHT_RANGES = {
  human: [60, 90],
  elf: [59, 77],
  dwarf: [60, 82],
  goblin: [21, 24],
  halfling: [19, 26],
  orc: [50, 90],
  drow: [38, 60],
  gnome: [17, 21],
  highelf: [59, 82],
  darkelf: [37, 70],
};

// https://www.name-generator.org.uk/?i=94f4alm
export const TOWNS_ARRAY = [
  {
    name: 'Springbourne',
    description: 'Springbourne is a sprawling town, known for a famous invention.',
    mainRace: 'dwarf',
  },
  {
    name: 'Grand Gansil',
    description: 'Grand Gansil is a sprawling town, known for its historic significance.',
    mainRace: 'human',
  },
  {
    name: 'Viewcliffe',
    description: 'Viewcliffe is a small city, known for its historic significance.',
    mainRace: 'highelf',
  },
  {
    name: 'Nyou Under Amthag Creek',
    description: 'Nyou Under Amthag Creek is a sprawling town on the edge of a beautiful estuary. It is known for its culture.',
    mainRace: 'elf',
  },
  {
    name: 'Windge-In-Tuswycombe',
    description: 'Windge-In-Tuswycombe is a sprawling town, known for its car factory.',
    mainRace: 'halfling',
  },
  {
    name: 'South Lkshammont Aux Bansswor',
    description: 'South Lkshammont Aux Bansswor is a large town, known for its chocolate.',
    mainRace: 'drow',
  },
  {
    name: 'Chladepre-In-Clilake',
    description: 'Chladepre-In-Clilake is a sprawling town situated besides a lake. It is known for UFO reports.',
    mainRace: 'orc',
  },
  {
    name: 'Great Trapoint-In-Huthorpe',
    description: 'Great Trapoint-In-Huthorpe is a sprawling town, known for the Great Trapoint-In-Huthorpe music festival.',
    mainRace: 'darkelf',
  },
  {
    name: 'Mount Bexnkport',
    description: 'Mount Bexnkport is a coastal, large town, known for its chocolate.',
    mainRace: 'gnome',
  },
  {
    name: 'West Wells',
    description: 'West Wells is a sprawling city, known for being the birthplace of a famous detective.',
    mainRace: 'goblin',
  },
];

export const PROFESSIONS_ARRAY = [
  'Metalworker',
  'Brewer',
  'Cook',
  'Carpenter',
  'Smelter',
  'Mason',
  'Baker',
  'Butcher',
  'Tinker',
  'Tax inspector',
  'Blacksmith',
  'Stonecarver',
  'Prospector',
  'Farmer',
  'Potter',
  'Tailor',
  'Sculptor',
  'Miner',
  'Medic',
  'Gemcutter',
  'Woodcarver',
  'Mechanic',
  'Leatherworker',
  'Marble Carver',
];

export const COLOR_NAMES = [
  'AliceBlue',
  'AntiqueWhite',
  'Aqua',
  'Aquamarine',
  'Azure',
  'Beige',
  'Bisque',
  'Black',
  'BlanchedAlmond',
  'Blue',
  'BlueViolet',
  'Brown',
  'BurlyWood',
  'CadetBlue',
  'Chartreuse',
  'Chocolate',
  'Coral',
  'CornflowerBlue',
  'Cornsilk',
  'Crimson',
  'Cyan',
  'DarkBlue',
  'DarkCyan',
  'DarkGoldenRod',
  'DarkGray',
  'DarkGrey',
  'DarkGreen',
  'DarkKhaki',
  'DarkMagenta',
  'DarkOliveGreen',
  'DarkOrange',
  'DarkOrchid',
  'DarkRed',
  'DarkSalmon',
  'DarkSeaGreen',
  'DarkSlateBlue',
  'DarkSlateGray',
  'DarkSlateGrey',
  'DarkTurquoise',
  'DarkViolet',
  'DeepPink',
  'DeepSkyBlue',
  'DimGray',
  'DimGrey',
  'DodgerBlue',
  'FireBrick',
  'FloralWhite',
  'ForestGreen',
  'Fuchsia',
  'Gainsboro',
  'GhostWhite',
  'Gold',
  'GoldenRod',
  'Gray',
  'Grey',
  'Green',
  'GreenYellow',
  'HoneyDew',
  'HotPink',
  'IndianRed',
  'Indigo',
  'Ivory',
  'Khaki',
  'Lavender',
  'LavenderBlush',
  'LawnGreen',
  'LemonChiffon',
  'LightBlue',
  'LightCoral',
  'LightCyan',
  'LightGoldenRodYellow',
  'LightGray',
  'LightGrey',
  'LightGreen',
  'LightPink',
  'LightSalmon',
  'LightSeaGreen',
  'LightSkyBlue',
  'LightSlateGray',
  'LightSlateGrey',
  'LightSteelBlue',
  'LightYellow',
  'Lime',
  'LimeGreen',
  'Linen',
  'Magenta',
  'Maroon',
  'MediumAquaMarine',
  'MediumBlue',
  'MediumOrchid',
  'MediumPurple',
  'MediumSeaGreen',
  'MediumSlateBlue',
  'MediumSpringGreen',
  'MediumTurquoise',
  'MediumVioletRed',
  'MidnightBlue',
  'MintCream',
  'MistyRose',
  'Moccasin',
  'NavajoWhite',
  'Navy',
  'OldLace',
  'Olive',
  'OliveDrab',
  'Orange',
  'OrangeRed',
  'Orchid',
  'PaleGoldenRod',
  'PaleGreen',
  'PaleTurquoise',
  'PaleVioletRed',
  'PapayaWhip',
  'PeachPuff',
  'Peru',
  'Pink',
  'Plum',
  'PowderBlue',
  'Purple',
  'RebeccaPurple',
  'Red',
  'RosyBrown',
  'RoyalBlue',
  'SaddleBrown',
  'Salmon',
  'SandyBrown',
  'SeaGreen',
  'SeaShell',
  'Sienna',
  'Silver',
  'SkyBlue',
  'SlateBlue',
  'SlateGray',
  'SlateGrey',
  'Snow',
  'SpringGreen',
  'SteelBlue',
  'Tan',
  'Teal',
  'Thistle',
  'Tomato',
  'Turquoise',
  'Violet',
  'Wheat',
  'White',
  'WhiteSmoke',
  'Yellow',
  'YellowGreen',
];

/**
  * Hardcoded array of strings for genders
*/
export const GENDER_OPTIONS = [
  'Androginous',
  'Agender',
  'Bigender',
  'Female',
  'Male',
  'Female To Male',
  'Genderqueer',
  'Male to Female',
  'Other',
  'Pangender',
  'Third Gender',
  'Transgender',
  'Transsexual',
  'Two-Spirit',
];
